swagger: "2.0"
info:
  version: v1alpha
  title: Ridge Container Service API
  description: An API for managing containers
basePath: /rcs/v1alpha
host: api.ridge.co
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: API Server Status
    description: An API for checking the server status.
  - name: Container Presets
    description: Pre-defined sets of container types.
  - name: Batches
    description: Operations on Batches.
  - name: Containers
    description: Operations on Containers.
paths:
  /status:
    get:
      operationId: status
      summary: Check if API Server is Ready to Serve Requests
      description: If the API server is ready to serve requests, the response code 204 HTTP is returned.
      tags:
        - API Server Status
      responses:
        204:
          description: OK
        403:
          description: Forbidden
          schema:
            type: string
  /container-presets:
    get:
      operationId: listContainerPresets
      summary: List Container Presets
      description: Returns a list of the container presets (suggested container sizes).
      tags:
        - Container Presets
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/container_presets'
  /orgs/{org}/projects/{project}/batches:
    parameters:
      - name: org
        in: path
        description: The organization identifier.
        required: true
        type: string
      - name: project
        in: path
        description: The project identifier.
        required: true
        type: string
    get:
      operationId: listBatches
      summary: List Batches
      description: Returns a list of all the batches that have been created for the specified project.
      tags:
        - Batches
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/batches'
        401:
          description: Unauthorized
          schema:
            type: string
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: Resource not found
          schema:
            type: string
    post:
      operationId: createBatch
      summary: Create a Batch
      description: Creates a new batch of containers in the specified project.
      tags:
        - Batches
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/batch_create'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/batch'
        400:
          description: Bad request parameter
          schema:
            type: string
        401:
          description: Unauthorized
          schema:
            type: string
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: Resource not found
          schema:
            type: string
  /orgs/{org}/projects/{project}/batches/{batch}:
    parameters:
      - name: org
        in: path
        description: The organization identifier.
        required: true
        type: string
      - name: project
        in: path
        description: The project identifier.
        required: true
        type: string
      - name: batch
        in: path
        description: A unique identifier of a batch.
        type: string
        required: true
    get:
      operationId: describeBatch
      summary: Describe a Batch
      description: Returns information about a specific batch.
      tags:
        - Batches
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/batch'
        401:
          description: Unauthorized
          schema:
            type: string
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: Resource not found
          schema:
            type: string
    patch:
      operationId: updateBatch
      summary: Update a Batch
      description: Update the batch properties.
      tags:
        - Batches
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/batch_update'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/batch'
        400:
          description: Invalid request parameters
          schema:
            type: string
        401:
          description: Unauthorized
          schema:
            type: string
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: Resource not found
          schema:
            type: string
    delete:
      operationId: deleteBatch
      summary: Delete a Batch
      description: Deletes the selected batch including all its containers.
      tags:
        - Batches
      responses:
        204:
          description: OK
        400:
          description: Bad request.
          schema:
            type: string
        401:
          description: Unauthorized
          schema:
            type: string
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: Resource not found
          schema:
            type: string
  /orgs/{org}/projects/{project}/batches/{batch}/containers:
    parameters:
      - name: org
        in: path
        description: The organization identifier.
        required: true
        type: string
      - name: project
        in: path
        description: The project identifier.
        required: true
        type: string
      - name: batch
        in: path
        description: The batch identifier.
        required: true
        type: string
    get:
      operationId: listBatchContainers
      summary: List the containers in a Batch
      description: Returns a list of all containers in the batch.
      tags:
      - Containers
      parameters:
        - name: state
          in: query
          description: Filter the containers by the specified states.
          type: array
          items:
            type: string
            enum:
            - creating
            - starting
            - running
            - terminating
            - terminated
          default: [creating, starting, running, terminating]
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/containers'
        400:
          description: Invalid request parameters
          schema:
            type: string
        403:
          description: Forbidden
          schema:
            type: string
        401:
          description: Unauthorized
          schema:
            type: string
        404:
          description: Resource not found
          schema:
            type: string
  /orgs/{org}/projects/{project}/batches/{batch}/containers/{container}:
    parameters:
      - name: org
        in: path
        description: The organization identifier.
        required: true
        type: string
      - name: project
        in: path
        description: The project identifier.
        required: true
        type: string
      - name: batch
        in: path
        description: The batch identifier.
        type: string
        required: true
      - name: container
        in: path
        description: The unique identifier of a container.
        type: string
        required: true
    get:
      operationId: describeContainer
      summary: Describe a Container
      description: Returns information about the specified container.
      tags:
        - Containers
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/container'
        401:
          description: Unauthorized
          schema:
            type: string
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: Resource not found
          schema:
            type: string
    delete:
      operationId: terminateContainer
      summary: Terminate a Container
      description: Terminates the specified container.
      tags:
        - Containers
      responses:
        204:
          description: OK
        401:
          description: Unauthorized
          schema:
            type: string
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: Resource not found
          schema:
            type: string
definitions:
  batch_create:
    type: object
    required:
      - name
      - container_image
      - number
    properties:
      name:
        description: A user-readable name of the batch.
        type: string
        minLength: 1
        maxLength: 63
        pattern: '^[a-z]([-a-z0-9]*[a-z0-9])?$'
      display_name:
        description: The display name of the batch.
        type: string
        maxLength: 512
      number:
        description: The requested number of containers.
        type: integer
        minimum: 0
      container_image:
        description: The path where the container image can be found.
        type: string
        minLength: 1
        example: myregistry.local:5000/testing/test-image
      env:
        $ref: '#/definitions/env'
      entry_point:
        description: An entry point that overrides the default one provided by the container image.
        type: string
      args:
        description: Arguments that override the default ones provided by the container image. If you define args, but do not define an entry point, the default one is used with these arguments.
        type: array
        items:
          type: string
      docker_credentials_id:
        description: The ID of Docker credentials to access the container-image repository.
        type: string
      docker_credentials_path:
        description: The path of Docker credentials to access the container-image repository.
        type: string
      elasticsearch_endpoint:
        description: URL of Elastic Search instance to send logs produced by containers.
        type: string
        example: http://elasticsearch.example.com:9200
      aws_role:
        $ref: '#/definitions/aws_role'
      container_preset:
        description: The preset container type.
        type: string
      locations:
        description: One or more locations. A location can refer to a country, a subdivision of a country, or a city. A country is encoded using the Country codes (ISO-3166-1). A country subdivision as encoded as a <country code>-<subdivision code> (subdivision codes are defined in ISO-3166-2). A city is encoded as <country code>-<subdivision code>-<city name>. For example, US-MA-Boston. In cases where there is no subdivision in the country it will be left blank. For example IL--TelAviv.
        type: array
        items:
          type: string
      data_center_id:
        description: The ID of a data center to run the containers.
        type: string
      data_center_path:
        description: The data center path to run the containers.
        type: string
        example: /partner/foo/data-center/bar
      catalog_item_id:
        description: The VM catalog item ID. May only be specified if data center is specified.
        type: string
      catalog_item_path:
        description: The VM catalog item path. May only be specified if data center is specified.
        type: string
        example: /partners/big-partner/data-center/boston/vm-catalog/@7g167ryep3fr8ejr4bxemxju4h
      qualities:
        $ref: '#/definitions/quality_set'
      quantities:
        $ref: '#/definitions/quantity_set'
  batch_spec:
    type: object
    required:
      - name
      - container_image
      - number
    properties:
      name:
        description: A user-readable name of the batch.
        type: string
        minLength: 1
        maxLength: 63
        pattern: '^[a-z]([-a-z0-9]*[a-z0-9])?$'
      display_name:
        description: The display name of the batch.
        type: string
        maxLength: 512
      deleted:
        description: Indicates if this batch was deleted.
        type: boolean
      number:
        description: The requested number of containers.
        type: integer
        minimum: 0
      container_image:
        description: The path where the container image can be found.
        type: string
        minLength: 1
        example: myregistry.local:5000/testing/test-image
      env:
        $ref: '#/definitions/env'
      entry_point:
        description: An entry point that overrides the default one provided by the container image.
        type: string
      args:
        description: Arguments that override the default ones provided by the container image. If you define args, but do not define an entry point, the default one is used with these arguments.
        type: array
        items:
          type: string
      docker_credentials_id:
        description: The ID of Docker credentials to access the container-image repository.
        type: string
      docker_credentials_path:
        description: The path of Docker credentials to access the container-image repository.
        type: string
      elasticsearch_endpoint:
        description: URL of Elastic Search instance where logs produced by containers are sent.
        type: string
        example: http://elasticsearch.example.com:9200
      aws_role:
        $ref: '#/definitions/aws_role'
      container_preset:
        description: The preset container type. Will only be provided if it was specified at creation.
        type: string
      locations:
        description: One or more locations. A location can refer to a country, a subdivision of a country, or a city. A country is encoded using the Country codes (ISO-3166-1). A country subdivision as encoded as a <country code>-<subdivision code> (subdivision codes are defined in ISO-3166-2). A city is encoded as <country code>-<subdivision code>-<city name>. For example, US-MA-Boston. In cases where there is no subdivision in the country it will be left blank. For example IL--TelAviv.
        type: array
        items:
          type: string
      data_center_id:
        description: The ID of a data center to run the containers.
        type: string
      data_center_path:
        description: The data center path to run the containers.
        type: string
        example: /partner/foo/data-center/bar
      catalog_item_id:
        description: The VM catalog item ID.
        type: string
      catalog_item_path:
        description: The VM catalog item path.
        type: string
        example: /partners/big-partner/data-center/boston/vm-catalog/@7g167ryep3fr8ejr4bxemxju4h
      qualities:
        $ref: '#/definitions/quality_set'
      quantities:
        $ref: '#/definitions/quantity_set'
  batch_status:
    type: object
    required:
      - id
      - path
      - org_id
      - project_id
      - created_at
      - updated_at
      - state
      - number
    properties:
      id:
        description: The unique ID of the batch.
        type: string
      path:
        description: The path to the resource that includes all the parents
        type: string
        example: /orgs/my-org/projects/my-project/batches/my-batch
      org_id:
        description: The unique identifier of the organization.
        type: string
      project_id:
        description: The unique identifier of the project.
        type: string
      created_at:
        description: The time at which this batch was created.
        type: string
        format: date-time
      updated_at:
        description: The time at which this batch was last updated.
        type: string
        format: date-time
      state:
        description: The current state of the batch.
        type: string
        enum:
          - creating
          - fulfilling
          - fulfilled
          - failed
      number:
        description: The actual number of running or completed containers.
        type: integer
      data_center_id:
        description: The ID of a data center to run the containers.
        type: string
      data_center_path:
        description: The data center path to run the containers.
        type: string
        example: /partner/foo/data-center/bar
      shortage:
        description: Indicates the batch is not fully provisioned due to a shortage at the data center.
        type: boolean
      out_of_quota:
        description: Indicates the batch is not fully provisioned due to quota limitation.
        type: boolean
  batch:
    type: object
    required:
      - spec
      - status
    properties:
      spec:
        $ref: '#/definitions/batch_spec'
      status:
        $ref: '#/definitions/batch_status'
    example:
      spec:
        name: batch1
        display_name: Batch 1
        container_image: docker.io/library/bash:latest
        env:
        - FOO=bar
        args:
        - "/bin/sleep"
        - '360'
        elasticsearch_endpoint: http://elasticsearch.example.com:9200
        number: 3
        locations:
        data_center_id: n6wicf
        catalog_item_id: s1r37s
        catalog_item_path: "/partners/medone/data-centers/ptv/vm-catalog/@s1r37s"
      status:
        id: jizh77chbfcnyu7p79omf5rx5a
        path: "/orgs/test-org/projects/sandbox/batches/batch1"
        org_id: di86ihycue5875pb7d5ybfhn9r
        project_id: g3ker86kt6mir8rbczwkyjotpe
        created_at: '2021-03-08T16:29:06.265Z'
        updated_at: '2021-03-08T16:29:06.265Z'
        state: fulfilled
        number: 3
        data_center_id: n6wicf
        data_center_path: "/partners/medone/data-centers/ptv"
  batch_update:
    type: object
    properties:
      name:
        description: A human-readable name of the batch.
        type: string
        minLength: 1
        maxLength: 63
        pattern: '^[a-z]([-a-z0-9]*[a-z0-9])?$'
      display_name:
        description: The display name of the batch.
        type: string
        maxLength: 512
      #      desired_number:
      #        description: The desired number of containers.
      #        type: integer
      #        minimum: 0
      aws_role:
        $ref: '#/definitions/aws_role'
        x-nullable: true
    example:
      name: batch1
      display_name: Batch 1
  batches:
    description: A list of batches.
    type: object
    required:
      - items
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/batch'
  container:
    type: object
    required:
      - id
      - batch_id
      - path
      - org_id
      - project_id
      - data_center_id
      - data_center_path
      - state
    properties:
      id:
        description: A unique identifier of a container.
        type: string
      batch_id:
        description: The batch to which this container belongs.
        type: string
      path:
        description: The path to the resource that includes all the parents.
        type: string
        example: /orgs/my-org/projects/my-project/containers/@cxh5jywfn7y5tdj76go8ijxh7a
      org_id:
        description: The unique identifier of the organization.
        type: string
      project_id:
        description: The unique identifier of the project.
        type: string
      data_center_id:
        description: The data center in which the container is provisioned.
        type: string
      data_center_path:
        description: The path to the data center in which this container is provisioned, that includes all the parents.
        type: string
        example: /partner/foo/data-center/bar
      quantities:
        $ref: '#/definitions/quantity_set'
      started_at:
        description: The time when the container has been started.
        type: string
        format: date-time
      terminated_at:
        description: The time when the container has been terminated.
        type: string
        format: date-time
      state:
        description: The state of the container.
        type: string
        enum:
          - creating
          - starting
          - running
          - terminating
          - terminated
      state_reason:
        description: Information on why the container has reached its state.
        type: string
      exit_code:
        description: Exit code of containerized application.
        type: integer
      error:
        description: Error which occurred during container's lifetime.
        type: string
      shortage:
        description: Indicates the container is not fully provisioned due to a shortage at the data center.
        type: boolean
      degraded:
        description: The container is running in a degraded mode. There might be a delay between issuing a command for controlling this container and a response.
        type: boolean
    example:
      id: bg3c131wpdrjbi5ugmosis4aqy
      batch_id: jizh77chbfcnyu7p79omf5rx5a
      path: "/orgs/test-org/projects/sandbox/batches/batch1/containers/@bg3c131wpdrjbi5ugmosis4aqy"
      org_id: di86ihycue5875pb7d5ybfhn9r
      project_id: g3ker86kt6mir8rbczwkyjotpe
      data_center_id: n6wicf
      data_center_path: "/partners/medone/data-centers/ptv"
      start_time: '2021-03-08T16:35:22.899Z'
      state: running
  containers:
    type: object
    required:
      - items
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/container'
    example:
      items:
        - id: bg3c131wpdrjbi5ugmosis4aqy
          batch_id: jizh77chbfcnyu7p79omf5rx5a
          path: "/orgs/test-org/projects/sandbox/batches/batch1/containers/@bg3c131wpdrjbi5ugmosis4aqy"
          org_id: di86ihycue5875pb7d5ybfhn9r
          project_id: g3ker86kt6mir8rbczwkyjotpe
          data_center_id: n6wicf
          data_center_path: "/partners/medone/data-centers/ptv"
          start_time: '2021-03-08T16:35:22.899Z'
          state: running
        - id: ftapca1guorg77dooqzkoh14te
          batch_id: jizh77chbfcnyu7p79omf5rx5a
          path: "/orgs/test-org/projects/sandbox/batches/batch1/containers/@ftapca1guorg77dooqzkoh14te"
          org_id: di86ihycue5875pb7d5ybfhn9r
          project_id: g3ker86kt6mir8rbczwkyjotpe
          data_center_id: n6wicf
          data_center_path: "/partners/medone/data-centers/ptv"
          start_time: '2021-03-08T16:35:21.868Z'
          state: running
        - id: rooaohnuc8hk7zeafkb8az8mww
          batch_id: jizh77chbfcnyu7p79omf5rx5a
          path: "/orgs/test-org/projects/sandbox/batches/batch1/containers/@rooaohnuc8hk7zeafkb8az8mww"
          org_id: di86ihycue5875pb7d5ybfhn9r
          project_id: g3ker86kt6mir8rbczwkyjotpe
          data_center_id: n6wicf
          data_center_path: "/partners/medone/data-centers/ptv"
          start_time: '2021-03-08T16:35:31.169Z'
          state: running
  aws_role:
    type: object
    required:
      - role_arn
      - aws_access_key_id
    description: The AWS IAM role ans the AWS credentials that will be used to grant the container permission to access AWS services. The container will receive temporary credentials.
    properties:
      role_arn:
        description: The unique identifier of the role in AWS.
        type: string
      aws_access_key_id:
        description: The unique identifier of the AWS key that should be used to create temporary credentials for the container.
        type: string
  container_presets:
    description: A list of container presets.
    type: object
    required:
      - items
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/container_preset'
  container_preset:
    type: object
    required:
      - name
      - display_name
      - quantities
    properties:
      name:
        description: The human readable name of this preset.
        type: string
        minLength: 1
        maxLength: 63
        pattern: '^[a-z]([-a-z0-9]*[a-z0-9])?$'
      display_name:
        description: The display name of this preset.
        type: string
        maxLength: 512
      quantities:
        $ref: '#/definitions/quantity_set'
    example:
      name: xsmall
      display_name: X-Small
      quantities:
        cpu_cores: 1
        instance_storage: 10737418240
        ram: 1073741824
  env:
    description: A list of environment variables to be passed to the containers, usually in the form <name>=<value>.
    type: array
    items:
      type: string
      example: FOO=bar
  quality_set:
    description: A set of required qualities. The object maps quality identifiers to values. For qualities defined with no values, the value must be 1. See https://api.ridge.co/compute/v1alpha/qualities for possible properties.
    type: object
    additionalProperties:
      type: integer
  quantity_set:
    description: A set of quantities. The object maps quantity identifiers to values. See https://api.ridge.co/compute/v1alpha/quantities for possible properties.
    type: object
    additionalProperties:
      type: integer
      format: int64
